
import { Category, Crisis } from './types';

const NATURE: Crisis[] = [
  { id: "klimawandel", name: "Klimawandel", category: Category.NATURE },
  { id: "umweltzerstoerung", name: "Umweltzerstörung", category: Category.NATURE },
  { id: "biodiversitaetsverlust", name: "Biodiversitätsverlust", category: Category.NATURE },
  { id: "artensterben", name: "Artensterben", category: Category.NATURE },
  { id: "wasserknappheit", name: "Wasserknappheit", category: Category.NATURE },
  { id: "energieknappheit", name: "Energieknappheit", category: Category.NATURE },
  { id: "ressourcenerschoepfung", name: "Ressourcenerschöpfung", category: Category.NATURE },
  { id: "bodenversiegelung", name: "Bodenversiegelung", category: Category.NATURE },
  { id: "naturkatastrophen", name: "Naturkatastrophen", category: Category.NATURE },
  { id: "klimaflucht", name: "Klimaflucht", category: Category.NATURE },
  { id: "pandemie", name: "Pandemie", category: Category.NATURE },
  { id: "ozeanversauerung", name: "Ozeanversauerung", category: Category.NATURE },
  { id: "extraktivismus", name: "Extraktivismus", category: Category.NATURE },
];

const POWER: Crisis[] = [
  { id: "krieg", name: "Krieg", category: Category.POWER },
  { id: "militarisierung", name: "Militarisierung", category: Category.POWER },
  { id: "aufrüstung", name: "Aufrüstung", category: Category.POWER },
  { id: "geopolitische-verschiebungen", name: "Geopolitische Verschiebungen", category: Category.POWER },
  { id: "atomare-abschreckung", name: "Atomare Abschreckung", category: Category.POWER },
  { id: "stellvertreterkriege", name: "Stellvertreterkriege", category: Category.POWER },
  { id: "grenzkonflikte", name: "Grenzkonflikte", category: Category.POWER },
  { id: "terrorismus", name: "Terrorismus", category: Category.POWER },
  { id: "politische-gewaltfantasien", name: "Politische Gewaltfantasien", category: Category.POWER },
  { id: "populismus", name: "Populismus", category: Category.POWER },
  { id: "faschisierung", name: "Faschisierung", category: Category.POWER },
  { id: "identitaere-bewegungen", name: "Identitäre Bewegungen", category: Category.POWER },
  { id: "ethnonationalismus", name: "Ethnonationalismus", category: Category.POWER },
  { id: "autoritarismus", name: "Autoritarismus", category: Category.POWER },
  { id: "demokratieabbau", name: "Demokratieabbau", category: Category.POWER },
  { id: "korruption", name: "Korruption", category: Category.POWER },
  { id: "machtmissbrauch", name: "Machtmissbrauch", category: Category.POWER },
  { id: "vertrauensverlust", name: "Vertrauensverlust", category: Category.POWER },
  { id: "legitimationsverlust", name: "Legitimationsverlust", category: Category.POWER },
  { id: "post-demokratie", name: "Post-Demokratie", category: Category.POWER },
];

const SOCIETY: Crisis[] = [
  { id: "inflation", name: "Inflation", category: Category.SOCIETY },
  { id: "rezession", name: "Rezession", category: Category.SOCIETY },
  { id: "finanzialisierung", name: "Finanzialisierung", category: Category.SOCIETY },
  { id: "schuldenlast", name: "Schuldenlast", category: Category.SOCIETY },
  { id: "armut", name: "Armut", category: Category.SOCIETY },
  { id: "soziale-ungleichheit", name: "Soziale Ungleichheit", category: Category.SOCIETY },
  { id: "prekarisierung", name: "Prekarisierung", category: Category.SOCIETY },
  { id: "wohnraummangel", name: "Wohnraummangel", category: Category.SOCIETY },
  { id: "lieferkettenabhaengigkeit", name: "Lieferkettenabhängigkeit", category: Category.SOCIETY },
  { id: "infrastrukturverfall", name: "Infrastrukturverfall", category: Category.SOCIETY },
  { id: "migration", name: "Migration", category: Category.SOCIETY },
  { id: "grenzregime", name: "Grenzregime", category: Category.SOCIETY },
  { id: "abschiebungsapparat", name: "Abschiebungsapparat", category: Category.SOCIETY },
  { id: "entmenschlichung-buerokratie", name: "Entmenschlichung durch Bürokratie", category: Category.SOCIETY },
  { id: "lagerlogik", name: "Lagerlogik", category: Category.SOCIETY },
  { id: "asylpolitik", name: "Asylpolitik", category: Category.SOCIETY },
  { id: "staatsbuergerschaft", name: "Staatsbürgerschaft", category: Category.SOCIETY },
  { id: "exklusion", name: "Exklusion", category: Category.SOCIETY },
  { id: "illegale-arbeit", name: "Illegale Arbeit", category: Category.SOCIETY },
  { id: "rechtlosigkeit", name: "Rechtlosigkeit", category: Category.SOCIETY },
  { id: "care", name: "Care", category: Category.SOCIETY },
  { id: "drogen", name: "Drogen", category: Category.SOCIETY },
  { id: "gentrifizierung", name: "Gentrifizierung", category: Category.SOCIETY },
  { id: "bildungsungleichheit", name: "Bildungsungleichheit", category: Category.SOCIETY },
  { id: "demografischer-wandel", name: "Demografischer Wandel", category: Category.SOCIETY },
  { id: "alterung", name: "Alterung", category: Category.SOCIETY },
  { id: "pflegenotstand", name: "Pflegenotstand", category: Category.SOCIETY },
  { id: "rentenkrise", name: "Altersvorsorge", category: Category.SOCIETY },
  { id: "generationenkonflikt", name: "Generationenkonflikt", category: Category.SOCIETY },
];

const TECH: Crisis[] = [
  { id: "kuenstliche-intelligenz", name: "Künstliche Intelligenz", category: Category.TECH },
  { id: "algorithmische-steuerung", name: "Algorithmische Steuerung", category: Category.TECH },
  { id: "automatisierung", name: "Automatisierung", category: Category.TECH },
  { id: "digitalisierung", name: "Digitalisierung", category: Category.TECH },
  { id: "plattformoekonomie", name: "Plattformökonomie", category: Category.TECH },
  { id: "ueberwachung", name: "Überwachung", category: Category.TECH },
  { id: "datenmissbrauch", name: "Datenmissbrauch", category: Category.TECH },
  { id: "cyberangriffe", name: "Cyberangriffe", category: Category.TECH },
  { id: "technologische-intransparenz", name: "Technologische Intransparenz", category: Category.TECH },
  { id: "kontrollverlust", name: "Kontrollverlust", category: Category.TECH },
  { id: "transhumanismus", name: "Transhumanismus", category: Category.TECH },
];

const MIND: Crisis[] = [
  { id: "desinformation", name: "Desinformation", category: Category.MIND },
  { id: "propaganda", name: "Propaganda", category: Category.MIND },
  { id: "postfaktizitaet", name: "Postfaktizität", category: Category.MIND },
  { id: "medienerosion", name: "Medienerosion", category: Category.MIND },
  { id: "fragmentierung-der-oeffentlichkeit", name: "Fragmentierung der Öffentlichkeit", category: Category.MIND },
  { id: "polarisierung", name: "Polarisierung", category: Category.MIND },
  { id: "radikalisierung", name: "Radikalisierung", category: Category.MIND },
  { id: "aufmerksamkeitsoekonomie", name: "Aufmerksamkeitsökonomie", category: Category.MIND },
  { id: "empoerungsdynamiken", name: "Empörungsdynamiken", category: Category.MIND },
  { id: "zensur", name: "Zensur", category: Category.MIND },
  { id: "identitaetspolitik", name: "Identitätspolitik", category: Category.MIND },
  { id: "sprachregime", name: "Sprachregime", category: Category.MIND },
  { id: "normkonflikte", name: "Normkonflikte", category: Category.MIND },
  { id: "koerperpolitik", name: "Körperpolitik", category: Category.MIND },
  { id: "biopolitische-zuschreibungen", name: "Biopolitische Zuschreibungen", category: Category.MIND },
  { id: "symbolische-uebercodierung", name: "Symbolische Übercodierung", category: Category.MIND },
  { id: "sinnverlust", name: "Sinnverlust", category: Category.MIND },
  { id: "vereinsamung", name: "Vereinsamung", category: Category.MIND },
  { id: "psychische-belastung", name: "Psychische Belastung", category: Category.MIND },
  { id: "erschoepfung", name: "Erschöpfung", category: Category.MIND },
  { id: "zukunftsangst", name: "Zukunftsangst", category: Category.MIND },
  { id: "entfremdung", name: "Entfremdung", category: Category.MIND },
  { id: "nihilismus", name: "Nihilismus", category: Category.MIND },
];

export const CRISES: Crisis[] = [
  ...NATURE,
  ...POWER,
  ...SOCIETY,
  ...TECH,
  ...MIND,
];
